name: 没有比人更高的山
description: "Where there is a will, there is a way"
meta_description: "周亮的博客, Zhou Liang, Ruby on Rails，Java，Android, iOS"

markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: true
logo: false


# Details for the RSS feed generator
rss_name: 'feed/index.xml'
url:            'http://zhouliang.pro'
author:         '周亮'
author_description: '程序员，毕业于华中科技大学，喜欢折腾技术'
copyright: '除非另有声明，本网站采用<a href="http://creativecommons.org/licenses/by/3.0/cn/">知识共享“署名 3.0 中国大陆”许可协议</a>授权。'


baseurl: '/'
permalink: /:year/:month/:day/:title

paginate_path: /page/:num
paginate: 15

safe: false
cdn_url: http://7xj0lk.com1.z0.glb.clouddn.com/

JB:
  ASSET_PATH: false
  IMAGE_PATH: false
