name: 没有比人更高的山
description: "Where there is a will, there is a way"
meta_description: "周亮的博客, Zhou Liang, Ruby on Rails，Java，Android, iOS"

markdown: redcarpet
pygments: true
logo: false


# Details for the RSS feed generator
rss_name: 'feed.rss'
url:            'http://zhouliang.pro'
author:         '周亮'
author_description: '现就职于乐视网，前亚马逊中国软件研发工程师，华中科技大学电信系研究生，Dian团队第二任队长，华中科技大学OPhone俱乐部首任主席，擅长Ruby/Rails/Java开发，喜欢iOS设备与开发。'
copyright: '除非另有声明，本网站采用<a href="http://creativecommons.org/licenses/by/3.0/cn/">知识共享“署名 3.0 中国大陆”许可协议</a>授权。'


baseurl: 
permalink: /:year/:month/:day/:title

paginate_path: /page/:num
paginate: 15